_base_: "federated_base.yaml"
dataset: "ptbxl"
model: "cnn1d"

ptbxl:
  label_mode: "binary"
  num_classes: 2
  class_names: ["Normal", "Abnormal"]

training:
  augment: false
  batch_size: 96
  num_workers: 4
  pin_memory: true
  lr: 0.001
  weight_decay: 0.0005

federation:
  rounds: 30
  local_epochs: 5
  num_clients: 5
  fedbn_central_eval: "client_avg"

dp:
  target_delta: 1.0e-5
  max_grad_norm: 1.0
  max_physical_batch_size: 96

sweep:
  seed: 42
  partitions:
    - name: "label_skew_c1"
      fn: "label_skew"
      kwargs: {classes_per_client: 1}
    - name: "dirichlet_a01"
      fn: "dirichlet"
      kwargs: {alpha: 0.1}

  method_eps_matrix:
    - ["dp_fedavg",           "fedavg",           "fedavg", "inf"]
    - ["dp_fedavg",           "fedavg",           "fedavg", 3.0]
    - ["dp_fedavg",           "fedavg",           "fedavg", 1.0]
    - ["dp_fedavg_groupnorm", "fedavg_groupnorm", "fedavg", "inf"]
    - ["dp_fedavg_groupnorm", "fedavg_groupnorm", "fedavg", 3.0]
    - ["dp_fedavg_groupnorm", "fedavg_groupnorm", "fedavg", 1.0]
    - ["dp_fedbn",            "fedbn",            "fedbn",  "inf"]
    - ["dp_fedbn",            "fedbn",            "fedbn",  3.0]
    - ["dp_fedbn",            "fedbn",            "fedbn",  1.0]
